
development:
  adapter: postgresql
  encoding: unicode
  database: similizer_development
  pool: 5
<<<<<<< HEAD
  username: derekdigioia
=======
  username: vincent
>>>>>>> 7a743f0bb9ce9e726747dc20aa59f835cde29728
  password:



production:

  adapter: postgresql
  encoding: unicode
  database: similizer_test
  pool: 5
<<<<<<< HEAD
  username: derekdigioia
=======
  username: vincent
>>>>>>> 7a743f0bb9ce9e726747dc20aa59f835cde29728
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: similizer_production
  pool: 5
<<<<<<< HEAD
  username: derekdigioia
=======
  username: vincent
>>>>>>> 7a743f0bb9ce9e726747dc20aa59f835cde29728
  password:
