
development:
  adapter: postgresql
  encoding: unicode
  database: similizer_development
  pool: 5

  username: vincent
  password:



production:

  adapter: postgresql
  encoding: unicode
  database: similizer_test
  pool: 5
  username: vincent
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: similizer_production
  pool: 5
  username: vincent
  password:
